#!/bin/bash
#
#    fortinet-configure-openstack
#    Copyright (C) 2016 Fortinet  Ltd.
#
#    Authors: Nicolas Thomss  <nthomasfortinet.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -ex

cat << EOF
This script configure the following on openstack:
  - a network and subnet called mgmt
  - a keypair called default using ~/.ssh/id_rsa.pub
  - security group called default globally open.
EOF


#PKGS=" python-keystone python-neutronclient python-novaclient python-glanceclient python-openstackclient python-heatclient"
#dpkg -l $PKGS > /dev/null || sudo apt install -y $PKGS



NEUTRON_FIXED_NET_CIDR="192.168.1.0/24"
NEUTRON_DNS="8.8.8.8"

# Determine the tenant id for the configured tenant name.

echo "Configuring Openstack Neutron"

#Create mgmt network for neutron for tenant VMs
openstack network show mgmt > /dev/null 2>&1 || openstack network create mgmt
openstack subnet show mgmt_subnet > /dev/null 2>&1 || openstack subnet create mgmt_subnet --network mgmt --subnet-range $NEUTRON_FIXED_NET_CIDR --dns-nameserver $NEUTRON_DNS --dhcp
SUBNET_ID=$(openstack subnet show mgmt_subnet | grep " id" | awk '{print $4}')

#Configure the default security group to allow ICMP and SSH
openstack security group rule create --proto icmp default || echo "should have been created already"

##make wide open
openstack security group rule create --ingress  --ethertype IPv4 --remote-ip 0.0.0.0/0 default|| echo "should have been created already"
openstack security group rule create --ingress  --ethertype IPv4 --remote-ip 0.0.0.0/0 --protocol udp  default|| echo "should have been created already"

openstack security group rule create --ingress  --ethertype IPv6 --remote-ip ::/0  --protocol tcp default|| echo "should have been created already"
openstack security group rule create --ingress  --ethertype IPv6 --remote-ip ::/0  --protocol udp default|| echo "should have been created already"


#Upload a default SSH key
openstack keypair create  --public-key ~/.ssh/id_rsa.pub default  || echo "asssuming key is already uploaded"



